# 白名单，只记录这个人，优先级最高 例['用户名1', '用户名2', ...]
white_list: []
# 黑名单，不记录这个人，优先级第二高 例['用户名1', '用户名2', ...]
black_list: []
# 最低卡片等级，小于这个等级的跳过不记录，如果为空则全量抓取
min_card_level: 700
# 最高争夺等级，当对手为850满级卡时的争夺等级，目前最高争夺加成等级为1100
max_kf_level: 1100
# 在此日期前的跳过不记录，如果为空则全量抓取，因为3s环境变化较快不建议设置太久远
# 如记录中存在2023年3月10日前的数据，请勿填空或设置为2023年3月10日前，因为之前的数据格式未适配
last_date: '2023-05-05'
# 护符配置，格式 角色_武器: 护符或角色: 护符，当未精确匹配到武器时使用角色的护符，都未匹配使用default属性的值
amulet_config:
  default: ''
  MO: 'AGI 80 INT 80 SPR 80 MATK 10 SLD 10 RFL 10 PDEF 10 MDEF 10 AAA 4'
  LIN: 'VIT 80 MND 80 HP 10 RFL 10 PDEF 10 MDEF 10 AAA 4'
  AI: 'AGI 60 INT 60 VIT 60 MND 60 HP 10 SPD 10 REC 10 RFL 10 SKL 10 CRT 10 PDEF 10 MDEF 10 AAA 4'
  WEI: 'AGI 60 INT 60 VIT 60 MND 60 HP 10 SPD 10 SLD 10 REC 10 CRT 10 SKL 10 AAA 4'
  MING: 'STR 60 AGI 60 VIT 60 MND 60 HP 10 REC 10 PATK 10 SPD 10 RFL 10 CRT 10 SKL 10 MDEF 10 AAA 4'
  MIN: 'STR 50 AGI 50 INT 50 VIT 50 MND 50 HP 10 PATK 10 RFL 10 SKL 10 CRT 10 PDEF 10 MDEF 10 AAA 4'
  MENG: 'AGI 80 INT 80 SPR 80 SLD 10 SPD 10 CRT 10 SKL 10 AAA 4'
  XI: 'STR 60 AGI 60 VIT 60 MND 60 HP 10 PATK 10 SPD 10 RFL 10 CRT 10 SKL 10 PDEF 10 MDEF 10 AAA 4'
  YI: 'STR 60 AGI 60 VIT 60 MND 60 HP 10 PATK 10 SPD 10 RFL 10 CRT 10 SKL 10 PDEF 10 MDEF 10 AAA 4'
  XIA: 'AGI 80 INT 80 SPR 80 SLD 10 SPD 10 MATK 10 CRT 10 SKL 10 RFL 10 AAA 4'
  WU: 'STR 60 AGI 60 VIT 60 MND 60 HP 10 SPD 10 PATK 10 CRT 10 SKL 10 PDEF 10 MDEF 10 AAA 4'
  YA: 'STR 60 AGI 60 VIT 60 MND 60 HP 10 SPD 10 PATK 10 CRT 10 SKL 10 RFL 10 PDEF 10 MDEF 10 AAA 4'
# 默认许愿池
wish_config: '90 90 90 90 90 90 90 90 90 40 40 40 40 40'
# 无视颜色默认携带神秘的装备，未填写的装备只有红装才会拥有神秘
default_gear_mystery: ['SHIELD', 'CLAYMORE', 'SPEAR', 'CAPE', 'THORN', 'DAGGER', 'WAND',
                       'TIARA', 'RIBBON', 'RING', 'DEVOUR', 'COLORFUL', 'CLOAK']
# 默认成长值
default_g: 80000
# 装备默认百分比，觉得欧狗多就设置的高些，注意设置的太高胜率容易尿崩
gear_config:
  STAFF: '150 150 150 150'
  BLADE: '90 140 150 150'
  ASSBOW: '100 150 150 120'
  DAGGER: '100 130 150 150'
  WAND: '125 125 125 150'
  SHIELD: '100 150 130 130'
  CLAYMORE: '110 110 150 150'
  SPEAR: '100 150 150 120'
  GLOVES: '150 150 150 150'
  BRACELET: '150 150 100 130'
  VULTURE: '125 125 125 150'
  CLOAK: '100 120 150 150'
  THORN: '150 110 110 150'
  WOOD: '150 120 120 120'
  CAPE: '150 150 110 110'
  SCARF: '150 150 150 150'
  TIARA: '150 150 110 110'
  RIBBON: '130 130 130 130'
  RING: '110 110 150 150'
  DEVOUR: '100 150 130 150'
  SWORD: '150 150 150 150'
  BOW: '150 150 150 150'
  PLATE: '150 150 150 150'
  LEATHER: '150 150 150 150'
  CLOTH: '150 150 150 150'
  COLORFUL: '100 120 150 150'
# 是否加入权重，会根据出现次数加入w值，目前匹配池不平均建议开启
is_add_w: true
# 指定普通雅的模式 0白天1黑夜
ya_mode: 1
# 装备映射
# 如果是自定义主题的装备，需要在这里补充映射
gear_map:
  探险者短杖: 'STAFF'
  狂信者的荣誉之刃: 'BLADE'
  反叛者的刺杀弓: 'ASSBOW'
  幽梦匕首: 'DAGGER'
  光辉法杖: 'WAND'
  荆棘剑盾: 'SHIELD'
  陨铁重剑: 'CLAYMORE'
  饮血长枪: 'SPEAR'
  探险者手套: 'GLOVES'
  命师的传承手环: 'BRACELET'
  秃鹫手套: 'VULTURE'
  旅法师的灵光袍: 'CLOAK'
  战线支撑者的荆棘重甲: 'THORN'
  复苏木甲: 'WOOD'
  挑战斗篷: 'CAPE'
  探险者头巾: 'SCARF'
  占星师的发饰: 'TIARA'
  天使缎带: 'RIBBON'
  海星戒指: 'RING'
  噬魔戒指: 'DEVOUR'
  探险者之剑: 'SWORD'
  探险者短弓: 'BOW'
  探险者铁甲: 'PLATE'
  探险者皮甲: 'LEATHER'
  探险者布甲: 'CLOTH'
  萌爪耳钉: 'RIBBON'
  荆棘盾剑: 'SHIELD'
  饮血魔剑: 'SPEAR'
  探险者手环: 'GLOVES'
  秃鹫手环: 'VULTURE'
  复苏战衣: 'WOOD'
  探险者耳环: 'SCARF'
  占星师的耳饰: 'TIARA'
  彩金长剑: 'COLORFUL'
  香木法杖: 'STAFF'
  妖刀血鸦: 'BLADE'
  深渊之弓: 'ASSBOW'
  黑曜石天黑剑: 'DAGGER'
  棒棒糖手杖: 'WAND'
  盖亚之斧: 'SHIELD'
  勇气星核剑: 'CLAYMORE'
  混沌之刃: 'SPEAR'
  毁灭之伤冥神枪: 'SPEAR'
  旅者手镯: 'GLOVES'
  旅者拳套: 'GLOVES'
  睿智手镯: 'BRACELET'
  朋克手镯: 'VULTURE'
  深红爪: 'VULTURE'
  魔导师的长袍: 'CLOAK'
  霸王树之棘针铠: 'THORN'
  翠绿灵衣: 'WOOD'
  黑玛瑙之祈装衣: 'CAPE'
  旅者耳环: 'SCARF'
  旅者头巾: 'SCARF'
  海神耳饰: 'TIARA'
  樱花的月夜簪: 'TIARA'
  精灵王护石: 'RIBBON'
  细冰姬的蝴蝶结: 'RIBBON'
  永恒绿戒: 'RING'
  深结晶变异水晶: 'DEVOUR'
  旅人剑: 'SWORD'
  猎人弓: 'BOW'
  重金属护甲: 'PLATE'
  皮革工作服: 'LEATHER'
  旅者长袍: 'CLOTH'
  辉光剑雅德玛斯: 'COLORFUL'

# 下面的设置最好不要乱动，除非你对游戏以及源码有足够的了解
# 卡片映射
card_map:
  默: 'MO'
  琳: 'LIN'
  艾: 'AI'
  梦: 'MENG'
  薇: 'WEI'
  冥: 'MING'
  命: 'MIN'
  伊: 'YI'
  希: 'XI'
  舞: 'WU'
  霞: 'XIA'
  雅: 'YA'
  雅(凶神): 'YA2'
# 天赋映射
talent_map:
  启程之誓: 'SHI'
  启程之心: 'XIN'
  启程之风: 'FENG'
  等级挑战: 'TIAO'
  等级压制: 'YA'
  破壁之心: 'BI'
  破魔之心: 'MO'
  复合护盾: 'DUN'
  鲜血渴望: 'XUE'
  削骨之痛: 'XIAO'
  圣盾祝福: 'SHENG'
  恶意抽奖: 'E'
  伤口恶化: 'SHANG'
  精神创伤: 'SHEN'
  铁甲尖刺: 'CI'
  忍无可忍: 'REN'
  热血战魂: 'RE'
  点到为止: 'DIAN'
  午时已到: 'WU'
  纸薄命硬: 'ZHI'
  沸血之志: 'FEI'
  波澜不惊: 'BO'
  飓风之力: 'JU'
  红蓝双刺: 'HONG'
  荧光护盾: 'JUE'
  后发制人: 'HOU'
  钝化锋芒: 'DUNH'
  自信回头: 'ZI'
  不动如山: 'SHAN'
# xpath设置
xpath_config:
    attr: '//div[contains(@class,''alert-info'')]/div//span[contains(@class,''label-outline'')]//text()'
    talent: '//div[contains(@class,''alert-info'')]/div//div[contains(@class,''fyg_tr'')]//text()'
    gear: '//button[contains(@class,''fyg_colpzbg'')]/@data-original-title'
    level: '//button[contains(@class,''fyg_colpzbg'')]//text()'
    color: '//button[contains(@class,''fyg_colpzbg'')]/@style'
# 正则设置
match_config:
    str: "(?<=).*?(?=力)"
    agi: "(?<=力).*?(?=敏)"
    int: "(?<=敏).*?(?=智)"
    vit: "(?<=智).*?(?=体)"
    spr: "(?<=体).*?(?=精)"
    mnd: "(?<=精).*?(?=意)"
    talent: "(?<=\\|).*?(?=\\|)"
    color: ".*/(.*)\\.gif.*"
# 输入文件路径
input_path: './source/'
# 输出文件路径
output_path: './source/pc.txt'



